### ISSUE TITLE
Spectrum 1.1.0 displays test case nested structure wrong in Intellij Idea

### ISSUE THREAD

**Issue by anttiahonen** [greghaskins/spectrum#110] opened 2017-03-23 13:52 UTC
Unfortunately version 1.1.0 seems to have introduced funky behavior in Intellij Idea test output structure in case of exception inside tests.

First the test code that throws exception:
[![spectrumkoodi.png](https://s28.postimg.org/y5mxz4dtp/spectrumkoodi.png)](https://postimg.org/image/d8qpugfsp/)
Second how Intellij Idea displays it with Spectrum 1.0.0
[![spectrum1.0.0.png](https://s30.postimg.org/b70h2uju9/spectrum1_0_0.png)](https://postimg.org/image/xiy9w8iy5/)
Third the same test with Spectrum 1.1.0
[![spectrum1.1.0.png](https://s2.postimg.org/xasg2w52h/spectrum1_1_0.png)](https://postimg.org/image/jh43duch1/)

Happens at least with Intellij Idea 2017.1 and 2016.3.5

**Comment by ashleyfrieze** [comment] 2017-03-24 00:44
This looks to be an issue with the way that Spectrum informs the `RunNotifier` about failure and where that happens in the process. The `RunNotifier` can be very picky about what you say to it and when. Looks like the more exotic `hook` mechanism we (and I mean _I_) added has some unexpected side effects when there are errors in the pre-test hooks.

@greghaskins do you mind if I investigate this over the next few days. Have any ideas of your own?

**Comment by greghaskins** [comment] 2017-03-24 00:56
@ashleyfrieze be my guest. Thanks for the help. I don't have any ideas off hand, but interested to see what you find.

**Comment by ashleyfrieze** [comment] 2017-03-24 01:01
I think it may also be related to #109 - I think we need to call `fireTestStarted` for a failing test to explain why it failed. My guess is that the solution to this may lay in abstracting away from `RunNotifier`, which can only help move toward test framework agnosticism.

I did a little spike, and it looks like it will need more than a one line fix :|

**Comment by ashleyfrieze** [comment] 2017-03-25 18:04
We're violating the contract with `RunNotifier` in a couple of ways. The hook mechanism would get very tangled if we didn't introduce an adapter.

I'm working on a branch here - https://github.com/ashleyfrieze/spectrum/tree/IntelliJErrorBug

Some of the problem is dealt with by 130b14873e91993a0c825505cc545af4406fabda

**Comment by ashleyfrieze** [comment] 2017-04-18 15:52
@anttiahonen if you would like to pull the branch behind #111 and try it on both of the issues you raised, I'd appreciate the feedback. I had reproduced your problem with this test:

https://github.com/ashleyfrieze/spectrum/blob/IntelliJErrorBug/src/test/java/specs/BeforeEachSpecs.java

That test didn't make it into my solution, though, since I produced a proxy for it which focused more on the root cause - the violation of the interface of `RunNotifier`. 

I think we're still deliberately violating that interface by pushing several failures to it relating to the same test, but perhaps that's not going to cause you any noticeable issues.

**Comment by greghaskins** [comment] 2017-04-21 15:10
@ashleyfrieze Unfortunately, this doesn't seem to be fully resolved after #111. I did a quick check by picking a spec at random and making it throw an exception to see how IntelliJ reports it. Looks like weird things are getting reported when something goes wrong in `beforeAll`:

<img width="1173" alt="screen shot 2017-04-21 at 9 53 59 am" src="https://cloud.githubusercontent.com/assets/285310/25280613/98cadb66-2678-11e7-8717-8518f8ff2265.png">

For comparison, with `1.0.2`, the reporting seems to do the right thing:

<img width="1174" alt="screen shot 2017-04-21 at 9 57 55 am" src="https://cloud.githubusercontent.com/assets/285310/25280863/653b3a92-2679-11e7-86e7-463742ffab12.png">

I'm going to check `afterAll` too, but haven't yet.

**Comment by ashleyfrieze** [comment] 2017-04-21 15:12
Looks like _someone_ is going to have to fix it some more. While I'm there I'll look at how JUnit mixins' `@BeforeAll` also works.

**Comment by greghaskins** [comment] 2017-04-26 17:58
Closed by #112

**Closed by greghaskins** 2017-04-26 17:58 UTC
